### ISSUE TITLE
Plugin installed for Vim but the colours are not showing up

### ISSUE THREAD

**Issue by wilsonsilva** [gleam-lang/gleam.vim#11]
I installed vim-plug and followed the instructions in this repo's README but I can't see the the Gleam colors:

ITerm2
<img width="682" alt="Screenshot 2024-05-24 at 12 03 01" src="https://github.com/gleam-lang/gleam.vim/assets/645203/1b815c15-9b57-41f7-9f00-4871164731e7">

Terminal.app
<img width="682" alt="Screenshot 2024-05-24 at 12 02 16" src="https://github.com/gleam-lang/gleam.vim/assets/645203/700f2ae4-7110-4718-9bfd-25227a539ae4">

```
:PlugInstall

- Finishing ... Done!
- gleam.vim: Already installed
```

```
> $ tree .vim
.vim
├── autoload
│   └── plug.vim
├── colors
│   └── railscasts.vim
└── plugged
    └── gleam.vim
        ├── LICENCE
        ├── README.md
        ├── compiler
        │   └── gleam.vim
        ├── ftdetect
        │   └── gleam.vim
        ├── ftplugin
        │   └── gleam.vim
        ├── snippets
        │   └── gleam.snippets
        └── syntax
            └── gleam.vim

10 directories, 9 files
```

```
> $ cat .vimrc
" Use 256 colors instead of 8
" let &t_Co=256

" Enable syntax coloring on OSX
" syntax on

" Use the railscasts color scheme
" colorscheme railscasts

" Show line numbers
" set number
" set mouse=a

"  ^ The configuration above is what I had before ^

" Install plugins
call plug#begin()

Plug 'gleam-lang/gleam.vim'

call plug#end()
```

MacOS 14.5 (23F79)

**Comment by lpil** [comment]
Sorry, what do you mean? You have syntax highlighting in your screenshots.

**Comment by wilsonsilva** [comment]
I do. But I don't have these colours

<img width="563" alt="Screenshot 2024-05-24 at 16 40 01" src="https://github.com/gleam-lang/gleam.vim/assets/645203/95199389-f1c5-452e-a6de-18d2015e02c9">

**Comment by lpil** [comment]
Ah! I use the [Duskfox](https://github.com/EdenEast/nightfox.nvim?tab=readme-ov-file#duskfox) theme
